---
configure_dotfiles: false
configure_osx: false

dotfiles_repo: https://github.com/drmanalo/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_repo_version: main
dotfiles_files:
  - .aerospace.toml
  - .gitignore
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - autoconf
  - bat
  - doxygen
  - eza
  - fzf
  - delta
  - gettext
  - git
  - gh
  - go
  - gpg
  - hashicorp/tap/terraform
  - httpie
  - hugo
  - iperf
  - libevent
  - mockery
  - neovim
  - nmap
  - node
  - nvm
  - ollama
  - pass
  - podman
  - powerlevel10k
  - pngpaste
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - speedtest-cli
  - sqlite
  - tldr
  - wget
  - wrk
  - zsh-autosuggestions
  - zsh-autocomplete

homebrew_taps: 
  - hashicorp/tap
  - nikitabobko/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - anythingllm
  - brave-browser
  - chromedriver
  - finch
  - firefox
  - font-meslo-lg-nerd-font
  - google-chrome
  - intellij-idea-ce
  - iterm2
  - kitty
  - licecap
  - nosql-workbench
  - nikitabobko/tap/aerospace
  - pycharm-ce
  - sequel-ace
  - slack
  - sublime-text
  - trilium-notes
  - visual-studio-code

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: wscat
    state: present
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []